### ISSUE TITLE
Not found `lib/index.js` after updating to `2.4.11`

### ISSUE THREAD

**Issue by stekycz** [matzkoh/prettier-plugin-packagejson#147]
After updating to `2.4.11` from `2.4.10` I am getting the following error

```
[error] Cannot find module '<...>/node_modules/prettier-plugin-packagejson/lib/index.js' imported from <...>/node_modules/prettier/index.mjs
```

It looks like the recently renamed file (`.js` -> `.cjs`) is not included in the published package or the plugin is missconfigured somewhere.

_Prettier version_: `3.2.5`

**Comment by matzkoh** [comment]
@stekycz 

Thanks for the report.
I could not reproduce it on my end.
Could you please create a minimal reproduction repository?

**Comment by stekycz** [comment]
Thank you for a quick reaction!

🤦‍♂️ My bad, the plugin is registered by using relative path `./node_modules/prettier-plugin-packagejson/lib/index.js` instead of simple `prettier-plugin-packagejson`. Will fix it on my side.
