### ISSUE TITLE
Using logic from sort-package-json

### ISSUE THREAD

**Issue by kachkaev** [matzkoh/prettier-plugin-packagejson#2]
Hi @matzkoh 👋 Thanks for this plugin!

WDYT of leveraging [`sort-package-json`](https://www.npmjs.com/package/sort-package-json) when figuring out the order of the keys? That tool seems to be quite popular, which means that it will likely cover various edge cases well. Using `sort-package-json` via your plugin and thus Prettier seem like a great synergy.

This would also solve https://github.com/keithamus/sort-package-json/issues/67 for me.

**Comment by matzkoh** [comment]
@kachkaev 

Perfect!
I will publish updates later.
Thank you for your suggestions!
