### ISSUE TITLE
2.1.X version breaking changes in minor update

### ISSUE THREAD

**Issue by SkeLLLa** [matzkoh/prettier-plugin-packagejson#21]
Prettier was updated to 2.0 and it's introduced a lot of breaking changes. So many users will still use prettier 1.9.X.

However this plugin has minor upgrade, so it may automatically upgraded by users with `npm up` and they will receive an error, cause prettier will have 1.9.X. If prettier-plugin-packagejson will have version 2.1.X and prettier will be at 1.9.X users will receive following error:
```
Cannot find module 'prettier/parser-babel'
```

Can you consider bumping major version of this plugin with updated prettier and update 2.1.1 with prettier 1.9.X?

**Comment by matzkoh** [comment]
> Cannot find module 'prettier/parser-babel'

It is a bug.
It is possible to support both v2 and v1.
I will release soon.

**Comment by SkeLLLa** [comment]
Great, thanks!
