### ISSUE TITLE
Doesn't appear to work under yarn v2

### ISSUE THREAD

**Issue by leaumar** [matzkoh/prettier-plugin-packagejson#37]
I've got some  projects with yarn v2 and several with v1 and pnpm, the latest prettier (I use renovate too), and this plugin. Prettier json-formats my package.json without fail, but this plugin's key sorting (e.g. script alphabetizing) never works under yarn v2. Your competitor, prettier-package-json, doesn't work either under yarn v2. I've tried prepending `yarn pnpify` to the command and declaring the plugin explicitly in .prettierrc.yml. Is there another config trick to get right to make it work, or is yarn v2 compatibility a work in progress?

**Comment by kachkaev** [comment]
This is a general issue with plugin autodiscovery in Yarn v2.

If you `require()` the plugin in prettier config, it will work! Details: https://github.com/prettier/prettier/issues/7073#issuecomment-712465373

**Comment by leaumar** [comment]
Thanks for the tip. Shame this requires js config, I prefer purely declarative config :c

**Comment by leaumar** [comment]
Seems my issue actually had 2 causes, after the config there's this: https://github.com/keithamus/sort-package-json/issues/220

I've overridden the version in my resolutions, so now it sorts scripts too. I was mistaken about your competitor, prettier-package-json isn't a prettier plugin (which explains why that didn't work), prettier-plugin-package is.

Now I've found that this plugin only works via CLI. Letting my IDE run prettier on file save does not reorder keys unless I use prettier-plugin-package instead. Not sure what that could be down to, my IDE env's nodejs is 14.16.0 (not the same as my terminal's where I run prettier's CLI) so probably not a compatibility thing. Just leaving this here for any other readers, and in case you feel like investigating why one works and the other doesn't. 🙂

**Comment by leaumar** [comment]
I'm actually getting some very confusing behavior. This plugin _does_ actually work under yarn v2 with yml config, just not on `scripts`, _not even with_ sort-package-json pinned to the old version that still sorts `scripts`, _unless_ you run it via CLI instead of on-save with your IDE. But with prettier-plugin-package it does always sort as expected.
