### ISSUE TITLE
Remove dependency on Prettier

### ISSUE THREAD

**Issue by mrmckeb** [matzkoh/prettier-plugin-packagejson#56]
Hi there, we maintain [vercel/style-guide](https://github.com/vercel/style-guide), and have just added this plugin.

Ideally, we want our users to be able to use our style guide package with or without Prettier, but this plugin has a peer-dependency on Prettier. On some package managers, like pnpm, this logs a warning.

We're more than happy to create a PR for this. The two options we think will solve this are:
1. Remove the peer dependency (unless you want to specify that for version compatibility).
1. Set the dependency to optional:
  ```json
  {
    "peerDependencies": {
      "prettier": ">= 1.16.0"
    },
    "peerDependenciesMeta": {
      "prettier": {
        "optional": true
      }
    }
  }
  ```

We'd love to hear your thoughts, thanks!

**Comment by matzkoh** [comment]
@mrmckeb 

Thank you for your suggestion.
I thought it would be better to make it optional in that we could specify a minimum version of prettier.
If that would accomplish your goal, I would welcome a PR!

**Comment by mrmckeb** [comment]
Thanks, PR created!
