### ISSUE TITLE
Allow passing options to sort-package-json

### ISSUE THREAD

**Issue by tunnckoCore** [matzkoh/prettier-plugin-packagejson#8]
So we can configure the sort order, through overrides

```js
{
  overrides: [
    {
      files: ['package.json'],
      options: {
        sortOrder: ['foo', 'bar'],
      },
    },
  ],
}
```

**Comment by kachkaev** [comment]
Hi @tunnckoCore 👋

There's been a similar discussion in this repo already, please see https://github.com/matzkoh/prettier-plugin-packagejson/issues/7#issuecomment-510814882

**Comment by tunnckoCore** [comment]
Who to know that title relates to such discussion. Anyway.

And yet, even Prettier allowed few options.

**Comment by kachkaev** [comment]
According to https://prettier.io/docs/en/option-philosophy.html, there are few options that are really unavoidable and a couple of those that have been added prematurely, but are hard to remove now. In general, there is a strong resistance in the community against adding new options; https://github.com/prettier/prettier/issues/40 is a good conversation to read on this.
