### ISSUE TITLE
Not working with Prettier 3.0.0-alpha.10 (after upgrading from 3.0.0-alpha.3)

### ISSUE THREAD

**Issue by kachkaev** [matzkoh/prettier-plugin-packagejson#80]
👋 @matzkoh!

Looks like this plugin has an issue with the most recent Prettier alpha. See https://github.com/prettier/prettier/issues/14753 for details. I thought it was an issue in Prettier core, but @fisker suggested that it was to do with the plugin. It'd be great if you could have a look!

**Comment by kachkaev** [comment]
Update: https://github.com/matzkoh/prettier-plugin-packagejson/pull/81#issuecomment-1521408208

**Comment by matzkoh** [comment]
Thanks for catching up!
This seems to have been resolved by the prettier side, so I will close it.
