### ISSUE TITLE
Does not work with prettier 3.0.0

### ISSUE THREAD

**Issue by jfairley** [matzkoh/prettier-plugin-packagejson#97]
I recently upgraded to `prettier` 3.0.0 and my `package.json` is no longer formatting. Prettier runs silently (no error or warning output), but clearly incorrect formatting does not get corrected.

Versions:
- node 18.17.0
- prettier 3.0.0
- prettier-plugin-packagejson 2.4.5

I downgraded to prettier 2.8.8, and my `package.json` formats.

related to #80 (maybe)

**Comment by nemchik** [comment]
I can confirm the same behavior with the same versions (and confirmed `prettier@2.8.8` works). I also tested `npx sort-package-json` which works regardless of any installed package versions.

**Comment by matzkoh** [comment]
I found that the plugin is not loaded.
It seems to work if I explicitly write plugins in the configuration file.
I will start working on this issue.

**Comment by matzkoh** [comment]
Since v3, plugins were no longer automatically searched. There is nothing that can be done here.
I will update the README.

https://github.com/prettier/prettier/pull/14759
